  - name: install mariadb package (Ubuntu)
    tags: ubuntu,db,mariadb
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb package (CentOS)
    tags: centos,db,mariadb
    yum:
      name:
        - mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.13.7/terraform_0.13.7_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root