  - name: install apache and php for ubuntu servers
    tags: apache,apache2,httpd
    package:
      name:
        - "{{ apache_package_name }}"
        - "{{ php_package_name }}"
      state: latest

  - name: start and enable apache service
    tags: apache,httpd
    service:
      name: "{{ apache_service }}"
      state: started
      enabled: yes

    # This one is here just to show an example
  - name: change e-mail address for admin
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin mert@joe.com
    # conf file is in a different directory for ubuntu
    when: ansible_distribution == "CentOS"
    notify: restart_apache

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      # directory name of "files" is assumed so we only need to include the file name
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644